(function (root, factory) {
  const expansion = factory();
  if (typeof module === "object" && module.exports) {
    module.exports = expansion;
  }
  if (root) {
    root.MOVIE_BRAWL_EXPANSION = expansion;
  }
})(typeof window !== "undefined" ? window : null, function () {
  const role = (data) => ({
    id: `role-${data.star}-${data.role}`,
    type: "role",
    region: "华语经典",
    rarity: data.rarity || "经典",
    keywords: data.keywords || [],
    effects: data.effects || [],
    deathEffects: data.deathEffects || [],
    ...data,
  });

  const spell = (data) => ({
    id: `neutral-${data.role}`,
    type: "spell",
    star: "通用",
    region: "片场",
    attack: 0,
    health: 0,
    keywords: data.keywords || [],
    effects: data.effects || [],
    deathEffects: [],
    ...data,
  });

  const weapon = (data) => ({
    id: `weapon-${data.role}`,
    type: "weapon",
    star: "通用",
    region: "银幕兵器",
    health: 0,
    keywords: data.keywords || [],
    effects: data.effects || [],
    deathEffects: [],
    ...data,
  });

  const roleCards = [
    role({
      star: "周星驰",
      role: "史提芬周",
      movie: "食神",
      cost: 5,
      attack: 4,
      health: 6,
      motif: "食",
      palette: "gold",
      text: "吸血。亡语：召唤两个 1/1 厨房学徒。",
      keywords: ["lifesteal", "deathrattle"],
      deathEffects: [{
        type: "summon",
        amount: 2,
        token: { role: "厨房学徒", attack: 1, health: 1, motif: "厨" },
      }],
    }),
    role({
      star: "成龙",
      role: "人字拖",
      movie: "宝贝计划",
      cost: 4,
      attack: 4,
      health: 4,
      motif: "护",
      palette: "azure",
      text: "嘲讽。亡语：召唤一个 2/2 护婴拍档。",
      keywords: ["taunt", "deathrattle"],
      deathEffects: [{
        type: "summon",
        amount: 1,
        token: { role: "护婴拍档", attack: 2, health: 2, motif: "婴" },
      }],
    }),
    role({
      star: "李连杰",
      role: "无名",
      movie: "英雄",
      cost: 5,
      attack: 5,
      health: 5,
      motif: "无",
      palette: "steel",
      text: "护盾。亡语：对敌方英雄造成 3 点伤害。",
      keywords: ["shield", "deathrattle"],
      deathEffects: [{ type: "damageEnemyHero", amount: 3 }],
    }),
    role({
      star: "周润发",
      role: "钟天正",
      movie: "监狱风云",
      cost: 4,
      attack: 3,
      health: 6,
      motif: "狱",
      palette: "bronze",
      text: "嘲讽。亡语：召唤一个 2/2 狱友。",
      keywords: ["taunt", "deathrattle"],
      deathEffects: [{
        type: "summon",
        amount: 1,
        token: { role: "狱友", attack: 2, health: 2, motif: "义" },
      }],
    }),
    role({
      star: "刘德华",
      role: "华仔",
      movie: "旺角卡门",
      cost: 3,
      attack: 4,
      health: 3,
      motif: "旺",
      palette: "crimson",
      text: "疾冲。亡语：对一个随机敌人造成 2 点伤害。",
      keywords: ["rush", "deathrattle"],
      deathEffects: [{ type: "damageRandomEnemy", amount: 2 }],
    }),
    role({
      star: "梁朝伟",
      role: "黎耀辉",
      movie: "春光乍泄",
      cost: 4,
      attack: 3,
      health: 5,
      motif: "黎",
      palette: "pink",
      text: "亡语：抽 2 张牌。",
      keywords: ["deathrattle"],
      deathEffects: [{ type: "draw", amount: 2 }],
    }),
    role({
      star: "张国荣",
      role: "十二少",
      movie: "胭脂扣",
      cost: 6,
      attack: 5,
      health: 6,
      motif: "少",
      palette: "violet",
      text: "亡语：召唤一个 4/4 如花幻影。",
      keywords: ["deathrattle"],
      deathEffects: [{
        type: "summon",
        amount: 1,
        token: { role: "如花幻影", attack: 4, health: 4, motif: "花" },
      }],
    }),
    role({
      star: "巩俐",
      role: "菊仙",
      movie: "霸王别姬",
      cost: 5,
      attack: 3,
      health: 7,
      motif: "菊",
      palette: "amber",
      text: "嘲讽。亡语：己方英雄恢复 4 点生命。",
      keywords: ["taunt", "deathrattle"],
      deathEffects: [{ type: "healHero", amount: 4 }],
    }),
    role({
      star: "章子怡",
      role: "王敏佳",
      movie: "无问西东",
      cost: 5,
      attack: 5,
      health: 6,
      motif: "敏",
      palette: "jade",
      text: "反伤 2：受到伤害后，对伤害来源造成 2 点伤害。",
      keywords: ["reflect"],
      reflect: 2,
    }),
    role({
      star: "葛优",
      role: "李冬宝",
      movie: "编辑部的故事",
      cost: 3,
      attack: 2,
      health: 5,
      motif: "编",
      palette: "teal",
      text: "亡语：获得一张随机通用卡。",
      keywords: ["deathrattle"],
      deathEffects: [{ type: "addRandomNeutral", amount: 1 }],
    }),
  ];

  const spellCards = [
    spell({
      role: "双雄合璧",
      movie: "群像片通用",
      cost: 4,
      motif: "合",
      palette: "gold",
      text: "融合两个友方角色，召唤属性相加并获得 +1/+1 的银幕双雄。",
      keywords: ["fusion"],
      requirements: { minFriendly: 2 },
      effects: [{
        type: "fuseFriendly",
        count: 2,
        bonusAttack: 1,
        bonusHealth: 1,
        role: "银幕双雄",
        motif: "合",
      }],
    }),
    spell({
      role: "宿命交锋",
      movie: "双主角通用",
      cost: 6,
      motif: "融",
      palette: "violet",
      text: "融合两个友方角色，融合角色获得嘲讽和吸血。",
      keywords: ["fusion"],
      requirements: { minFriendly: 2 },
      effects: [{
        type: "fuseFriendly",
        count: 2,
        bonusAttack: 0,
        bonusHealth: 2,
        role: "宿命主角",
        motif: "融",
        keywords: ["taunt", "lifesteal"],
      }],
    }),
    spell({
      role: "以牙还牙",
      movie: "动作片通用",
      cost: 2,
      motif: "返",
      palette: "crimson",
      text: "一个随机友方角色获得反伤 2。",
      requirements: { minFriendly: 1 },
      effects: [{ type: "grantReflectRandom", amount: 2 }],
    }),
    spell({
      role: "终场遗言",
      movie: "剧情片通用",
      cost: 2,
      motif: "言",
      palette: "steel",
      text: "一个随机友方角色获得亡语：对敌方英雄造成 2 点伤害。",
      requirements: { minFriendly: 1 },
      effects: [{
        type: "grantDeathEffectRandom",
        deathEffect: { type: "damageEnemyHero", amount: 2 },
      }],
    }),
    spell({
      role: "大场面爆破",
      movie: "动作片通用",
      cost: 5,
      motif: "爆",
      palette: "crimson",
      text: "对所有敌方角色造成 3 点伤害。",
      effects: [{ type: "damageAllEnemies", amount: 3 }],
    }),
    spell({
      role: "绝地重拍",
      movie: "续集通用",
      cost: 4,
      motif: "重",
      palette: "azure",
      text: "召唤一个 3/3、具有疾冲和亡语抽牌的替身主角。",
      effects: [{
        type: "summon",
        amount: 1,
        token: {
          role: "替身主角",
          attack: 3,
          health: 3,
          motif: "替",
          keywords: ["rush", "deathrattle"],
          deathEffects: [{ type: "draw", amount: 1 }],
        },
      }],
    }),
    spell({
      role: "反派独白",
      movie: "犯罪片通用",
      cost: 3,
      motif: "白",
      palette: "violet",
      text: "抽 2 张牌，并对敌方英雄造成 1 点伤害。",
      effects: [{ type: "draw", amount: 2 }, { type: "damageEnemyHero", amount: 1 }],
    }),
    spell({
      role: "金牌剪辑",
      movie: "片场通用",
      cost: 1,
      motif: "剪",
      palette: "teal",
      text: "抽 1 张牌，获得 1 点临时戏力。",
      effects: [{ type: "draw", amount: 1 }, { type: "gainTempMana", amount: 1 }],
    }),
    spell({
      role: "主角光环",
      movie: "商业片通用",
      cost: 4,
      motif: "主",
      palette: "gold",
      text: "所有友方角色 +1/+1 并获得护盾。",
      effects: [
        { type: "buffAllFriendly", attack: 1, health: 1 },
        { type: "shieldAllFriendly" },
      ],
    }),
    spell({
      role: "命运反转",
      movie: "传奇片通用",
      cost: 6,
      motif: "转",
      palette: "jade",
      text: "己方英雄恢复 6 点生命；对所有敌方角色造成 2 点伤害。",
      effects: [{ type: "healHero", amount: 6 }, { type: "damageAllEnemies", amount: 2 }],
    }),
  ];

  const weaponCards = [
    weapon({
      role: "金箍棒",
      movie: "大话西游",
      cost: 5,
      attack: 5,
      durability: 2,
      motif: "棒",
      palette: "gold",
      text: "5 点攻击，2 点耐久。",
    }),
    weapon({
      role: "青冥剑",
      movie: "卧虎藏龙",
      cost: 4,
      attack: 3,
      durability: 3,
      motif: "剑",
      palette: "jade",
      text: "吸血。3 点攻击，3 点耐久。",
      keywords: ["lifesteal"],
    }),
    weapon({
      role: "凌凌漆飞刀",
      movie: "国产凌凌漆",
      cost: 2,
      attack: 2,
      durability: 3,
      motif: "刀",
      palette: "steel",
      text: "装备：对一个随机敌人造成 1 点伤害。",
      effects: [{ type: "damageRandomEnemy", amount: 1 }],
    }),
    weapon({
      role: "小马哥双枪",
      movie: "英雄本色",
      cost: 4,
      attack: 4,
      durability: 2,
      motif: "枪",
      palette: "crimson",
      text: "装备：对敌方英雄造成 1 点伤害。",
      effects: [{ type: "damageEnemyHero", amount: 1 }],
    }),
    weapon({
      role: "赌神扑克牌",
      movie: "赌神",
      cost: 1,
      attack: 1,
      durability: 4,
      motif: "牌",
      palette: "azure",
      text: "装备：抽 1 张牌。",
      effects: [{ type: "draw", amount: 1 }],
    }),
    weapon({
      role: "倚天剑",
      movie: "倚天屠龙记之魔教教主",
      cost: 3,
      attack: 3,
      durability: 2,
      motif: "倚",
      palette: "violet",
      text: "装备：随机友方角色获得护盾。",
      effects: [{ type: "shieldRandomFriendly" }],
    }),
  ];

  return { roleCards, spellCards, weaponCards };
});
