(function (root, factory) {
  const expansion =
    typeof module === "object" && module.exports
      ? require("./expansion-data.js")
      : root?.MOVIE_BRAWL_EXPANSION;
  const builders =
    typeof module === "object" && module.exports
      ? require("./card-builders.js")
      : root?.MOVIE_BRAWL_CARD_BUILDERS;
  const studioRegistry =
    typeof module === "object" && module.exports
      ? require("./studio-registry.js")
      : root?.MOVIE_BRAWL_STUDIO_REGISTRY;
  const starter =
    typeof module === "object" && module.exports
      ? require("./starter-cards.js")
      : root?.MOVIE_BRAWL_STARTER_CARDS;
  const pool = factory(expansion, studioRegistry, starter, builders);
  if (typeof module === "object" && module.exports) {
    module.exports = pool;
  }
  if (root) {
    root.CARD_POOL = pool;
  }
})(
  typeof window !== "undefined" ? window : null,
  function (
    expansion = {},
    studioRegistry = { adventureCards: [] },
    starter = {},
    builders,
  ) {
  const { role } = builders.createCardBuilders({
    region: "华语经典",
    rarity: "经典",
    idFor: (type, data) => `role-${data.star}-${data.role}`,
  });
  const { spell } = builders.createCardBuilders({
    star: "通用",
    region: "片场",
    idFor: (type, data) => `neutral-${data.role}`,
  });

  const baseRoleCards = [
    role({
      star: "周星驰",
      role: "至尊宝",
      movie: "大话西游",
      cost: 5,
      attack: 5,
      health: 5,
      motif: "月",
      palette: "violet",
      text: "入场：对敌方英雄造成 2 点伤害。疾冲。",
      keywords: ["rush"],
      effects: [{ type: "damageEnemyHero", amount: 2 }],
    }),
    role({
      star: "周星驰",
      role: "唐伯虎",
      movie: "唐伯虎点秋香",
      cost: 4,
      attack: 2,
      health: 4,
      motif: "画",
      palette: "jade",
      text: "入场：抽 1 张牌，并使一个友方角色 +1/+1。",
      effects: [{ type: "draw", amount: 1 }, { type: "buffRandomFriendly", attack: 1, health: 1 }],
    }),
    role({
      star: "周星驰",
      role: "凌凌漆",
      movie: "国产凌凌漆",
      cost: 3,
      attack: 3,
      health: 3,
      motif: "刀",
      palette: "steel",
      text: "入场：对一个随机敌人造成 2 点伤害。",
      effects: [{ type: "damageRandomEnemy", amount: 2 }],
    }),
    role({
      star: "周星驰",
      role: "尹天仇",
      movie: "喜剧之王",
      cost: 2,
      attack: 2,
      health: 3,
      motif: "演",
      palette: "gold",
      text: "入场：抽 1 张牌。护盾。",
      keywords: ["shield"],
      effects: [{ type: "draw", amount: 1 }],
    }),
    role({
      star: "周星驰",
      role: "星仔",
      movie: "功夫",
      cost: 6,
      attack: 6,
      health: 6,
      motif: "掌",
      palette: "crimson",
      text: "入场：对所有敌方角色造成 1 点伤害。护盾。",
      keywords: ["shield"],
      effects: [{ type: "damageAllEnemies", amount: 1 }],
    }),

    role({
      star: "成龙",
      role: "陈家驹",
      movie: "警察故事",
      cost: 4,
      attack: 4,
      health: 4,
      motif: "警",
      palette: "azure",
      text: "疾冲。入场：对生命最低的敌方角色造成 1 点伤害。",
      keywords: ["rush"],
      effects: [{ type: "damageWeakestEnemyMinion", amount: 1 }],
    }),
    role({
      star: "成龙",
      role: "黄飞鸿",
      movie: "醉拳",
      cost: 5,
      attack: 4,
      health: 6,
      motif: "拳",
      palette: "amber",
      text: "吸血。入场：己方英雄恢复 3 点生命。",
      keywords: ["lifesteal"],
      effects: [{ type: "healHero", amount: 3 }],
    }),
    role({
      star: "成龙",
      role: "马如龙",
      movie: "A计划",
      cost: 3,
      attack: 2,
      health: 5,
      motif: "锚",
      palette: "teal",
      text: "嘲讽。入场：召唤一个 1/1 水手。",
      keywords: ["taunt"],
      effects: [{ type: "summon", amount: 1, token: { role: "水手", attack: 1, health: 1, motif: "海" } }],
    }),
    role({
      star: "成龙",
      role: "孟波",
      movie: "城市猎人",
      cost: 4,
      attack: 5,
      health: 3,
      motif: "猎",
      palette: "pink",
      text: "入场：随机敌人受到 3 点伤害。",
      effects: [{ type: "damageRandomEnemy", amount: 3 }],
    }),
    role({
      star: "成龙",
      role: "杰克",
      movie: "神话",
      cost: 6,
      attack: 5,
      health: 7,
      motif: "陵",
      palette: "bronze",
      text: "护盾。入场：抽 1 张牌。",
      keywords: ["shield"],
      effects: [{ type: "draw", amount: 1 }],
    }),

    role({
      star: "李连杰",
      role: "令狐冲",
      movie: "笑傲江湖之东方不败",
      cost: 4,
      attack: 4,
      health: 4,
      motif: "剑",
      palette: "jade",
      text: "疾冲。攻击后己方英雄恢复 1 点生命。",
      keywords: ["rush", "lifesteal"],
    }),
    role({
      star: "李连杰",
      role: "黄飞鸿",
      movie: "黄飞鸿",
      cost: 5,
      attack: 4,
      health: 5,
      motif: "狮",
      palette: "crimson",
      text: "嘲讽。入场：所有友方角色 +1 攻击。",
      keywords: ["taunt"],
      effects: [{ type: "buffAllFriendly", attack: 1, health: 0 }],
    }),
    role({
      star: "李连杰",
      role: "方世玉",
      movie: "方世玉",
      cost: 3,
      attack: 3,
      health: 4,
      motif: "擂",
      palette: "amber",
      text: "疾冲。入场：自身 +1 攻击。",
      keywords: ["rush"],
      effects: [{ type: "buffSelf", attack: 1, health: 0 }],
    }),
    role({
      star: "李连杰",
      role: "张无忌",
      movie: "倚天屠龙记之魔教教主",
      cost: 6,
      attack: 6,
      health: 7,
      motif: "乾",
      palette: "violet",
      text: "入场：所有敌方角色 -1 攻击。吸血。",
      keywords: ["lifesteal"],
      effects: [{ type: "weakenAllEnemies", amount: 1 }],
    }),
    role({
      star: "李连杰",
      role: "霍元甲",
      movie: "霍元甲",
      cost: 7,
      attack: 7,
      health: 7,
      motif: "武",
      palette: "steel",
      text: "嘲讽。入场：对所有敌方角色造成 2 点伤害。",
      keywords: ["taunt"],
      effects: [{ type: "damageAllEnemies", amount: 2 }],
    }),

    role({
      star: "周润发",
      role: "小马哥",
      movie: "英雄本色",
      cost: 5,
      attack: 6,
      health: 4,
      motif: "义",
      palette: "crimson",
      text: "疾冲。入场：随机敌人受到 2 点伤害。",
      keywords: ["rush"],
      effects: [{ type: "damageRandomEnemy", amount: 2 }],
    }),
    role({
      star: "周润发",
      role: "许文强",
      movie: "上海滩",
      cost: 4,
      attack: 3,
      health: 6,
      motif: "滩",
      palette: "azure",
      text: "嘲讽。入场：己方英雄恢复 2 点生命。",
      keywords: ["taunt"],
      effects: [{ type: "healHero", amount: 2 }],
    }),
    role({
      star: "周润发",
      role: "高进",
      movie: "赌神",
      cost: 6,
      attack: 6,
      health: 5,
      motif: "赌",
      palette: "gold",
      text: "入场：抽 2 张牌。",
      effects: [{ type: "draw", amount: 2 }],
    }),
    role({
      star: "周润发",
      role: "李慕白",
      movie: "卧虎藏龙",
      cost: 5,
      attack: 5,
      health: 5,
      motif: "青",
      palette: "jade",
      text: "护盾。疾冲。",
      keywords: ["shield", "rush"],
    }),
    role({
      star: "周润发",
      role: "阿郎",
      movie: "阿郎的故事",
      cost: 3,
      attack: 3,
      health: 4,
      motif: "车",
      palette: "bronze",
      text: "入场：己方英雄恢复 4 点生命。",
      effects: [{ type: "healHero", amount: 4 }],
    }),

    role({
      star: "刘德华",
      role: "华弟",
      movie: "天若有情",
      cost: 4,
      attack: 5,
      health: 3,
      motif: "车",
      palette: "pink",
      text: "疾冲。入场：自身 +1 生命。",
      keywords: ["rush"],
      effects: [{ type: "buffSelf", attack: 0, health: 1 }],
    }),
    role({
      star: "刘德华",
      role: "刘建明",
      movie: "无间道",
      cost: 3,
      attack: 3,
      health: 3,
      motif: "间",
      palette: "steel",
      text: "入场：随机敌方角色 -2 攻击。",
      effects: [{ type: "weakenRandomEnemy", amount: 2 }],
    }),
    role({
      star: "刘德华",
      role: "刀仔",
      movie: "赌侠",
      cost: 2,
      attack: 2,
      health: 3,
      motif: "牌",
      palette: "gold",
      text: "入场：抽 1 张牌。",
      effects: [{ type: "draw", amount: 1 }],
    }),
    role({
      star: "刘德华",
      role: "雷洛",
      movie: "五亿探长雷洛传",
      cost: 5,
      attack: 4,
      health: 7,
      motif: "探",
      palette: "azure",
      text: "嘲讽。入场：获得 1 点临时法力。",
      keywords: ["taunt"],
      effects: [{ type: "gainTempMana", amount: 1 }],
    }),
    role({
      star: "刘德华",
      role: "杨过",
      movie: "神雕侠侣",
      cost: 6,
      attack: 7,
      health: 5,
      motif: "雕",
      palette: "violet",
      text: "入场：对敌方英雄造成 3 点伤害。吸血。",
      keywords: ["lifesteal"],
      effects: [{ type: "damageEnemyHero", amount: 3 }],
    }),

    role({
      star: "梁朝伟",
      role: "陈永仁",
      movie: "无间道",
      cost: 4,
      attack: 3,
      health: 5,
      motif: "仁",
      palette: "steel",
      text: "入场：抽 1 张牌，并随机削弱一个敌方角色。",
      effects: [{ type: "draw", amount: 1 }, { type: "weakenRandomEnemy", amount: 1 }],
    }),
    role({
      star: "梁朝伟",
      role: "周慕云",
      movie: "花样年华",
      cost: 3,
      attack: 2,
      health: 5,
      motif: "巷",
      palette: "pink",
      text: "入场：所有友方角色 +1 生命。",
      effects: [{ type: "buffAllFriendly", attack: 0, health: 1 }],
    }),
    role({
      star: "梁朝伟",
      role: "盲武士",
      movie: "东邪西毒",
      cost: 5,
      attack: 6,
      health: 4,
      motif: "盲",
      palette: "bronze",
      text: "疾冲。攻击时具有吸血。",
      keywords: ["rush", "lifesteal"],
    }),
    role({
      star: "梁朝伟",
      role: "韦小宝",
      movie: "鹿鼎记",
      cost: 2,
      attack: 1,
      health: 4,
      motif: "宝",
      palette: "amber",
      text: "入场：召唤一个 1/1 侍卫。",
      effects: [{ type: "summon", amount: 1, token: { role: "侍卫", attack: 1, health: 1, motif: "卫" } }],
    }),
    role({
      star: "梁朝伟",
      role: "叶问",
      movie: "一代宗师",
      cost: 7,
      attack: 6,
      health: 8,
      motif: "咏",
      palette: "jade",
      text: "嘲讽。入场：所有友方角色获得护盾。",
      keywords: ["taunt"],
      effects: [{ type: "shieldAllFriendly" }],
    }),

    role({
      star: "张国荣",
      role: "程蝶衣",
      movie: "霸王别姬",
      cost: 5,
      attack: 4,
      health: 6,
      motif: "戏",
      palette: "crimson",
      text: "入场：抽 1 张牌。所有友方角色 +1 生命。",
      effects: [{ type: "draw", amount: 1 }, { type: "buffAllFriendly", attack: 0, health: 1 }],
    }),
    role({
      star: "张国荣",
      role: "宁采臣",
      movie: "倩女幽魂",
      cost: 3,
      attack: 2,
      health: 4,
      motif: "书",
      palette: "violet",
      text: "护盾。入场：己方英雄恢复 2 点生命。",
      keywords: ["shield"],
      effects: [{ type: "healHero", amount: 2 }],
    }),
    role({
      star: "张国荣",
      role: "旭仔",
      movie: "阿飞正传",
      cost: 2,
      attack: 3,
      health: 2,
      motif: "飞",
      palette: "teal",
      text: "疾冲。",
      keywords: ["rush"],
    }),
    role({
      star: "张国荣",
      role: "欧阳锋",
      movie: "东邪西毒",
      cost: 6,
      attack: 7,
      health: 5,
      motif: "沙",
      palette: "bronze",
      text: "入场：所有敌方角色 -1/-1。",
      effects: [{ type: "damageAllEnemies", amount: 1 }, { type: "weakenAllEnemies", amount: 1 }],
    }),
    role({
      star: "张国荣",
      role: "何宝荣",
      movie: "春光乍泄",
      cost: 4,
      attack: 4,
      health: 4,
      motif: "灯",
      palette: "pink",
      text: "入场：随机友方角色获得护盾。",
      effects: [{ type: "shieldRandomFriendly" }],
    }),

    role({
      star: "巩俐",
      role: "秋菊",
      movie: "秋菊打官司",
      cost: 3,
      attack: 2,
      health: 6,
      motif: "理",
      palette: "amber",
      text: "嘲讽。入场：己方英雄恢复 2 点生命。",
      keywords: ["taunt"],
      effects: [{ type: "healHero", amount: 2 }],
    }),
    role({
      star: "巩俐",
      role: "颂莲",
      movie: "大红灯笼高高挂",
      cost: 4,
      attack: 3,
      health: 6,
      motif: "灯",
      palette: "crimson",
      text: "入场：随机敌方角色失去 2 攻击。",
      effects: [{ type: "weakenRandomEnemy", amount: 2 }],
    }),
    role({
      star: "巩俐",
      role: "菊豆",
      movie: "菊豆",
      cost: 2,
      attack: 2,
      health: 3,
      motif: "染",
      palette: "jade",
      text: "入场：一个友方角色 +1/+1。",
      effects: [{ type: "buffRandomFriendly", attack: 1, health: 1 }],
    }),
    role({
      star: "巩俐",
      role: "女皇",
      movie: "满城尽带黄金甲",
      cost: 7,
      attack: 6,
      health: 8,
      motif: "冠",
      palette: "gold",
      text: "嘲讽。入场：所有友方角色 +1/+1。",
      keywords: ["taunt"],
      effects: [{ type: "buffAllFriendly", attack: 1, health: 1 }],
    }),
    role({
      star: "巩俐",
      role: "冯婉瑜",
      movie: "归来",
      cost: 3,
      attack: 1,
      health: 5,
      motif: "归",
      palette: "steel",
      text: "入场：己方英雄恢复 5 点生命。",
      effects: [{ type: "healHero", amount: 5 }],
    }),

    role({
      star: "章子怡",
      role: "玉娇龙",
      movie: "卧虎藏龙",
      cost: 5,
      attack: 6,
      health: 4,
      motif: "龙",
      palette: "jade",
      text: "疾冲。护盾。",
      keywords: ["rush", "shield"],
    }),
    role({
      star: "章子怡",
      role: "宫二",
      movie: "一代宗师",
      cost: 6,
      attack: 6,
      health: 6,
      motif: "宫",
      palette: "steel",
      text: "入场：对所有敌方角色造成 1 点伤害。吸血。",
      keywords: ["lifesteal"],
      effects: [{ type: "damageAllEnemies", amount: 1 }],
    }),
    role({
      star: "章子怡",
      role: "小妹",
      movie: "十面埋伏",
      cost: 4,
      attack: 5,
      health: 3,
      motif: "鼓",
      palette: "pink",
      text: "疾冲。入场：随机敌人受到 2 点伤害。",
      keywords: ["rush"],
      effects: [{ type: "damageRandomEnemy", amount: 2 }],
    }),
    role({
      star: "章子怡",
      role: "赵弟",
      movie: "我的父亲母亲",
      cost: 2,
      attack: 1,
      health: 4,
      motif: "路",
      palette: "amber",
      text: "入场：抽 1 张牌。",
      effects: [{ type: "draw", amount: 1 }],
    }),
    role({
      star: "章子怡",
      role: "白玲",
      movie: "2046",
      cost: 3,
      attack: 3,
      health: 4,
      motif: "窗",
      palette: "violet",
      text: "入场：随机友方角色 +2 攻击。",
      effects: [{ type: "buffRandomFriendly", attack: 2, health: 0 }],
    }),

    role({
      star: "葛优",
      role: "黎叔",
      movie: "天下无贼",
      cost: 4,
      attack: 3,
      health: 5,
      motif: "贼",
      palette: "steel",
      text: "入场：抽 1 张牌，敌方英雄受到 1 点伤害。",
      effects: [{ type: "draw", amount: 1 }, { type: "damageEnemyHero", amount: 1 }],
    }),
    role({
      star: "葛优",
      role: "秦奋",
      movie: "非诚勿扰",
      cost: 3,
      attack: 2,
      health: 5,
      motif: "缘",
      palette: "teal",
      text: "入场：己方英雄恢复 3 点生命。",
      effects: [{ type: "healHero", amount: 3 }],
    }),
    role({
      star: "葛优",
      role: "姚远",
      movie: "不见不散",
      cost: 2,
      attack: 2,
      health: 3,
      motif: "远",
      palette: "azure",
      text: "入场：获得 1 点临时法力。",
      effects: [{ type: "gainTempMana", amount: 1 }],
    }),
    role({
      star: "葛优",
      role: "严守一",
      movie: "手机",
      cost: 4,
      attack: 4,
      health: 4,
      motif: "机",
      palette: "bronze",
      text: "入场：随机敌方角色 -1 攻击，并抽 1 张牌。",
      effects: [{ type: "weakenRandomEnemy", amount: 1 }, { type: "draw", amount: 1 }],
    }),
    role({
      star: "葛优",
      role: "福贵",
      movie: "活着",
      cost: 6,
      attack: 4,
      health: 9,
      motif: "活",
      palette: "gold",
      text: "嘲讽。入场：己方英雄恢复 4 点生命。",
      keywords: ["taunt"],
      effects: [{ type: "healHero", amount: 4 }],
    }),
  ];

  const baseSpellCards = [
    spell({
      role: "场记板",
      movie: "片场通用",
      cost: 2,
      motif: "咔",
      palette: "steel",
      text: "抽 2 张牌。",
      effects: [{ type: "draw", amount: 2 }],
    }),
    spell({
      role: "爆米花补给",
      movie: "影院通用",
      cost: 1,
      motif: "米",
      palette: "amber",
      text: "己方英雄恢复 4 点生命。",
      effects: [{ type: "healHero", amount: 4 }],
    }),
    spell({
      role: "武术指导",
      movie: "动作片通用",
      cost: 3,
      motif: "武",
      palette: "crimson",
      text: "一个随机友方角色 +2 攻击并获得疾冲。",
      effects: [{ type: "buffRandomFriendly", attack: 2, health: 0 }, { type: "rushRandomFriendly" }],
    }),
    spell({
      role: "替身演员",
      movie: "片场通用",
      cost: 2,
      motif: "替",
      palette: "azure",
      text: "召唤一个 2/3 且具有嘲讽的替身。",
      effects: [{ type: "summon", amount: 1, token: { role: "替身演员", attack: 2, health: 3, motif: "替", keywords: ["taunt"] } }],
    }),
    spell({
      role: "威亚救场",
      movie: "动作片通用",
      cost: 2,
      motif: "绳",
      palette: "teal",
      text: "随机友方角色获得护盾。",
      effects: [{ type: "shieldRandomFriendly" }],
    }),
    spell({
      role: "经典台词",
      movie: "华语片通用",
      cost: 1,
      motif: "词",
      palette: "gold",
      text: "随机友方角色 +2 攻击。",
      effects: [{ type: "buffRandomFriendly", attack: 2, health: 0 }],
    }),
    spell({
      role: "导演喊卡",
      movie: "片场通用",
      cost: 3,
      motif: "停",
      palette: "violet",
      text: "随机敌方角色眩晕一回合。",
      effects: [{ type: "stunRandomEnemy" }],
    }),
    spell({
      role: "黄金档播出",
      movie: "电视剧通用",
      cost: 2,
      motif: "播",
      palette: "amber",
      text: "获得 2 点临时法力。",
      effects: [{ type: "gainTempMana", amount: 2 }],
    }),
    spell({
      role: "训练蒙太奇",
      movie: "类型片通用",
      cost: 4,
      motif: "练",
      palette: "jade",
      text: "所有友方角色 +1/+1。",
      effects: [{ type: "buffAllFriendly", attack: 1, health: 1 }],
    }),
    spell({
      role: "雨夜巷战",
      movie: "警匪片通用",
      cost: 4,
      motif: "雨",
      palette: "steel",
      text: "对所有敌方角色造成 2 点伤害。",
      effects: [{ type: "damageAllEnemies", amount: 2 }],
    }),
    spell({
      role: "群演入镜",
      movie: "片场通用",
      cost: 3,
      motif: "众",
      palette: "bronze",
      text: "召唤两个 1/1 群演。",
      effects: [{ type: "summon", amount: 2, token: { role: "群演", attack: 1, health: 1, motif: "众" } }],
    }),
    spell({
      role: "片尾彩蛋",
      movie: "商业片通用",
      cost: 2,
      motif: "彩",
      palette: "pink",
      text: "将一张随机通用卡置入手牌。",
      effects: [{ type: "addRandomNeutral", amount: 1 }],
    }),
    spell({
      role: "票房逆袭",
      movie: "院线通用",
      cost: 5,
      motif: "票",
      palette: "gold",
      text: "抽 1 张牌；所有友方角色获得护盾。",
      effects: [{ type: "draw", amount: 1 }, { type: "shieldAllFriendly" }],
    }),
    spell({
      role: "老戏骨压场",
      movie: "群像片通用",
      cost: 4,
      motif: "稳",
      palette: "jade",
      text: "召唤一个 3/5 且具有嘲讽的老戏骨。",
      effects: [{ type: "summon", amount: 1, token: { role: "老戏骨", attack: 3, health: 5, motif: "稳", keywords: ["taunt"] } }],
    }),
    spell({
      role: "主题曲响起",
      movie: "经典片通用",
      cost: 3,
      motif: "歌",
      palette: "crimson",
      text: "所有友方角色获得疾冲。",
      effects: [{ type: "rushAllFriendly" }],
    }),
    spell({
      role: "胶片倒带",
      movie: "怀旧片通用",
      cost: 3,
      motif: "回",
      palette: "violet",
      text: "己方英雄恢复 3 点生命，抽 1 张牌。",
      effects: [{ type: "healHero", amount: 3 }, { type: "draw", amount: 1 }],
    }),
  ];

  const roleCards = [...baseRoleCards, ...(expansion.roleCards || [])];
  const spellCards = [...baseSpellCards, ...(expansion.spellCards || [])];
  const weaponCards = [...(expansion.weaponCards || [])];
  const neutralCards = [...spellCards, ...weaponCards];
  const stars = [...new Set(roleCards.map((card) => card.star))].map((name) => ({
    name,
    cards: roleCards.filter((card) => card.star === name),
  }));

  return {
    roleCards,
    spellCards,
    weaponCards,
    neutralCards,
    adventureCards: studioRegistry.adventureCards,
    starterCards: starter.allCards || [],
    allCards: [
      ...roleCards,
      ...neutralCards,
      ...(starter.allCards || []),
      ...studioRegistry.adventureCards,
    ],
    stars,
  };
  },
);
