(function (root, factory) {
  const builders =
    typeof module === "object" && module.exports
      ? require("./card-builders.js")
      : root?.MOVIE_BRAWL_CARD_BUILDERS;
  const cards = factory(builders);
  if (typeof module === "object" && module.exports) {
    module.exports = cards;
  }
  if (root) {
    root.MOVIE_BRAWL_SHAW_CARDS = cards;
  }
})(typeof window !== "undefined" ? window : null, function (builders) {
  const { role, spell, weapon } = builders.studioCardBuilders({
    id: "shaw",
    region: "邵氏片场",
  });

  const normalCards = [
    role({
      star: "邵氏群像",
      role: "醉侠随从",
      movie: "大醉侠",
      cost: 2,
      attack: 2,
      health: 3,
      motif: "侠",
      palette: "amber",
      text: "入场：己方英雄恢复 2 点生命。",
      effects: [{ type: "healHero", amount: 2 }],
    }),
    spell({
      role: "客栈伏击",
      movie: "大醉侠",
      cost: 3,
      motif: "伏",
      palette: "crimson",
      text: "召唤两个 1/1 山寨喽啰。",
      effects: [{
        type: "summon",
        amount: 2,
        token: { role: "山寨喽啰", attack: 1, health: 1, motif: "寨" },
      }],
    }),
    weapon({
      role: "短锋剑",
      movie: "大醉侠",
      cost: 2,
      attack: 2,
      durability: 2,
      motif: "锋",
      palette: "steel",
      text: "装备：抽 1 张牌。",
      effects: [{ type: "draw", amount: 1 }],
    }),
    role({
      star: "邵氏群像",
      role: "血滴子死士",
      movie: "血滴子",
      cost: 3,
      attack: 3,
      health: 3,
      motif: "血",
      palette: "crimson",
      text: "亡语：对一个随机敌人造成 1 点伤害。",
      keywords: ["deathrattle"],
      deathEffects: [{ type: "damageRandomEnemy", amount: 1 }],
    }),
    spell({
      role: "飞索锁敌",
      movie: "血滴子",
      cost: 2,
      motif: "索",
      palette: "violet",
      text: "随机敌方角色眩晕一回合。",
      effects: [{ type: "stunRandomEnemy" }],
    }),
    weapon({
      role: "血滴子",
      movie: "血滴子",
      cost: 3,
      attack: 2,
      durability: 3,
      motif: "轮",
      palette: "crimson",
      text: "装备：对一个随机敌人造成 1 点伤害。",
      effects: [{ type: "damageRandomEnemy", amount: 1 }],
    }),
    role({
      star: "邵氏群像",
      role: "蜈蚣门徒",
      movie: "五毒",
      cost: 3,
      attack: 2,
      health: 4,
      motif: "蜈",
      palette: "jade",
      text: "反伤 1。",
      keywords: ["reflect"],
      reflect: 1,
    }),
    spell({
      role: "蛇形换位",
      movie: "五毒",
      cost: 2,
      motif: "蛇",
      palette: "jade",
      text: "随机友方角色获得护盾和疾冲。",
      effects: [
        { type: "shieldRandomFriendly" },
        { type: "rushRandomFriendly" },
      ],
    }),
    weapon({
      role: "毒门钢刺",
      movie: "五毒",
      cost: 2,
      attack: 2,
      durability: 2,
      motif: "刺",
      palette: "jade",
      text: "吸血。2 点攻击，2 点耐久。",
      keywords: ["lifesteal"],
    }),
    role({
      star: "邵氏群像",
      role: "金臂门卫",
      movie: "金臂童",
      cost: 4,
      attack: 3,
      health: 6,
      motif: "臂",
      palette: "gold",
      text: "嘲讽。",
      keywords: ["taunt"],
    }),
    spell({
      role: "铁布衫",
      movie: "金臂童",
      cost: 3,
      motif: "铁",
      palette: "gold",
      text: "所有友方角色 +0/+1，并获得护盾。",
      effects: [
        { type: "buffAllFriendly", attack: 0, health: 1 },
        { type: "shieldAllFriendly" },
      ],
    }),
    weapon({
      role: "金臂护腕",
      movie: "金臂童",
      cost: 3,
      attack: 3,
      durability: 2,
      motif: "腕",
      palette: "gold",
      text: "装备：随机友方角色 +1/+1。",
      effects: [{ type: "buffRandomFriendly", attack: 1, health: 1 }],
    }),
    role({
      star: "邵氏群像",
      role: "白莲弟子",
      movie: "洪文定三破白莲教",
      cost: 3,
      attack: 3,
      health: 4,
      motif: "莲",
      palette: "pink",
      text: "吸血。",
      keywords: ["lifesteal"],
    }),
    role({
      star: "邵氏群像",
      role: "莲台护法",
      movie: "洪文定三破白莲教",
      cost: 4,
      attack: 2,
      health: 7,
      motif: "护",
      palette: "violet",
      text: "嘲讽。亡语：己方英雄恢复 2 点生命。",
      keywords: ["taunt", "deathrattle"],
      deathEffects: [{ type: "healHero", amount: 2 }],
    }),
    spell({
      role: "回马枪",
      movie: "洪文定三破白莲教",
      cost: 3,
      motif: "回",
      palette: "steel",
      text: "对生命最低的敌方角色造成 3 点伤害。",
      effects: [{ type: "damageWeakestEnemyMinion", amount: 3 }],
    }),
  ];

  const bossCards = [
    role({
      star: "郑佩佩",
      role: "金燕子",
      movie: "大醉侠",
      cost: 4,
      attack: 4,
      health: 4,
      motif: "燕",
      palette: "gold",
      rarity: "头目",
      text: "疾冲。护盾。",
      keywords: ["rush", "shield"],
    }),
    role({
      star: "王羽",
      role: "方刚",
      movie: "独臂刀",
      cost: 5,
      attack: 5,
      health: 5,
      motif: "独",
      palette: "crimson",
      rarity: "头目",
      text: "疾冲。亡语：对敌方英雄造成 2 点伤害。",
      keywords: ["rush", "deathrattle"],
      deathEffects: [{ type: "damageEnemyHero", amount: 2 }],
    }),
    role({
      star: "刘家辉",
      role: "三德和尚",
      movie: "少林三十六房",
      cost: 7,
      attack: 5,
      health: 8,
      motif: "禅",
      palette: "amber",
      rarity: "最终头目",
      text: "嘲讽。入场：召唤两个 1/1 少林学徒。",
      keywords: ["taunt"],
      effects: [{
        type: "summon",
        amount: 2,
        token: { role: "少林学徒", attack: 1, health: 1, motif: "武" },
      }],
    }),
  ];

  return {
    normalCards,
    bossCards,
    allCards: [...normalCards, ...bossCards],
  };
});
