(function (root, factory) {
  const cards = factory();
  if (typeof module === "object" && module.exports) {
    module.exports = cards;
  }
  if (root) {
    root.MOVIE_BRAWL_STARTER_CARDS = cards;
  }
})(typeof window !== "undefined" ? window : null, function () {
  const role = (data) => ({
    id: `starter-role-${data.role}`,
    type: "role",
    star: "基础卡",
    region: data.region,
    rarity: "普通",
    keywords: data.keywords || [],
    effects: data.effects || [],
    deathEffects: [],
    starter: true,
    ...data,
  });

  const spell = (data) => ({
    id: `starter-spell-${data.role}`,
    type: "spell",
    star: "基础卡",
    region: data.region,
    rarity: "普通",
    attack: 0,
    health: 0,
    keywords: [],
    effects: data.effects || [],
    deathEffects: [],
    starter: true,
    ...data,
  });

  const weapon = (data) => ({
    id: `starter-weapon-${data.role}`,
    type: "weapon",
    star: "基础卡",
    region: data.region,
    rarity: "普通",
    health: 0,
    keywords: [],
    effects: data.effects || [],
    deathEffects: [],
    starter: true,
    ...data,
  });

  const allCards = [
    role({
      role: "普通群演",
      movie: "片场日常",
      region: "片场",
      cost: 1,
      attack: 1,
      health: 2,
      motif: "众",
      palette: "bronze",
      text: "没有技能，但随时准备入镜。",
    }),
    role({
      role: "巡街警员",
      movie: "警匪行动",
      region: "警匪",
      cost: 1,
      attack: 1,
      health: 2,
      motif: "巡",
      palette: "azure",
      text: "嘲讽。",
      keywords: ["taunt"],
    }),
    role({
      role: "酒馆伙计",
      movie: "江湖客栈",
      region: "武侠",
      cost: 1,
      attack: 1,
      health: 2,
      motif: "酒",
      palette: "amber",
      text: "入场：己方英雄恢复 1 点生命。",
      effects: [{ type: "healHero", amount: 1 }],
    }),
    spell({
      role: "临时加戏",
      movie: "片场日常",
      region: "片场",
      cost: 1,
      motif: "加",
      palette: "gold",
      text: "抽 1 张牌。",
      effects: [{ type: "draw", amount: 1 }],
    }),
    role({
      role: "替身演员",
      movie: "动作片场",
      region: "片场",
      cost: 2,
      attack: 2,
      health: 3,
      motif: "替",
      palette: "steel",
      text: "没有技能，胜在基本功扎实。",
    }),
    role({
      role: "喜剧搭档",
      movie: "市井喜剧",
      region: "喜剧",
      cost: 2,
      attack: 2,
      health: 1,
      motif: "笑",
      palette: "pink",
      text: "入场：召唤一个 1/1 捧哏。",
      effects: [{
        type: "summon",
        amount: 1,
        token: { role: "捧哏", attack: 1, health: 1, motif: "捧" },
      }],
    }),
    role({
      role: "镖局护卫",
      movie: "江湖武侠",
      region: "武侠",
      cost: 2,
      attack: 1,
      health: 4,
      motif: "镖",
      palette: "jade",
      text: "嘲讽。",
      keywords: ["taunt"],
    }),
    role({
      role: "年轻捕快",
      movie: "警匪行动",
      region: "警匪",
      cost: 2,
      attack: 2,
      health: 2,
      motif: "捕",
      palette: "azure",
      text: "疾冲。",
      keywords: ["rush"],
    }),
    weapon({
      role: "基础长棍",
      movie: "功夫训练",
      region: "功夫",
      cost: 2,
      attack: 2,
      durability: 2,
      motif: "棍",
      palette: "amber",
      text: "2 点攻击，2 点耐久。",
    }),
    role({
      role: "武馆教头",
      movie: "功夫训练",
      region: "功夫",
      cost: 3,
      attack: 3,
      health: 4,
      motif: "教",
      palette: "crimson",
      text: "没有技能，攻守均衡。",
    }),
    role({
      role: "客栈女侠",
      movie: "江湖武侠",
      region: "武侠",
      cost: 3,
      attack: 3,
      health: 3,
      motif: "侠",
      palette: "jade",
      text: "吸血。",
      keywords: ["lifesteal"],
    }),
    role({
      role: "重案探员",
      movie: "警匪行动",
      region: "警匪",
      cost: 3,
      attack: 3,
      health: 3,
      motif: "案",
      palette: "steel",
      text: "入场：对生命最低的敌方角色造成 1 点伤害。",
      effects: [{ type: "damageWeakestEnemyMinion", amount: 1 }],
    }),
    spell({
      role: "街坊助阵",
      movie: "市井喜剧",
      region: "喜剧",
      cost: 3,
      motif: "坊",
      palette: "pink",
      text: "召唤三个 1/1 街坊。",
      effects: [{
        type: "summon",
        amount: 3,
        token: { role: "街坊", attack: 1, health: 1, motif: "邻" },
      }],
    }),
  ];

  return { allCards };
});
