(function (root, factory) {
  const translations = factory();
  if (typeof module === "object" && module.exports) {
    module.exports = translations;
  }
  if (root) root.MOVIE_BRAWL_ENTITIES_EN = translations;
})(typeof window !== "undefined" ? window : null, function () {
  return {
    周星驰: "Stephen Chow",
    成龙: "Jackie Chan",
    李连杰: "Jet Li",
    周润发: "Chow Yun-fat",
    刘德华: "Andy Lau",
    梁朝伟: "Tony Leung Chiu-wai",
    张国荣: "Leslie Cheung",
    巩俐: "Gong Li",
    章子怡: "Zhang Ziyi",
    葛优: "Ge You",
    郑佩佩: "Cheng Pei-pei",
    王羽: "Jimmy Wang Yu",
    刘家辉: "Gordon Liu",
    通用: "Neutral",
    基础卡: "Basic Set",
    邵氏群像: "Shaw Ensemble",
    邵氏片场: "Shaw Studio",
    片场法术: "Studio Spell",
    银幕武器: "Screen Weapon",
    金像影迷: "Golden Reel Fan",
    反派制片方: "Villainous Producer",
    影迷: "Movie Fan",
    影迷英雄: "Movie Fan Hero",
    反派制片方英雄: "Villainous Producer Hero",
    至尊宝: "Joker",
    唐伯虎: "Tong Pak-fu",
    凌凌漆: "Ling Ling-chat",
    尹天仇: "Wan Tin-sau",
    星仔: "Sing",
    陈家驹: "Chan Ka-kui",
    黄飞鸿: "Wong Fei-hung",
    马如龙: "Dragon Ma",
    孟波: "Meng Bo",
    杰克: "Jack",
    令狐冲: "Linghu Chong",
    方世玉: "Fong Sai-yuk",
    张无忌: "Zhang Wuji",
    霍元甲: "Huo Yuanjia",
    小马哥: "Mark Lee",
    许文强: "Hui Man-keung",
    高进: "Ko Chun",
    李慕白: "Li Mu Bai",
    阿郎: "Ah-Long",
    华弟: "Wah Dee",
    华仔: "Ah Wah",
    刘建明: "Lau Kin-ming",
    刀仔: "Little Knife",
    雷洛: "Lee Rock",
    杨过: "Yang Guo",
    陈永仁: "Chan Wing-yan",
    周慕云: "Chow Mo-wan",
    盲武士: "Blind Swordsman",
    韦小宝: "Wai Siu-bo",
    叶问: "Ip Man",
    程蝶衣: "Cheng Dieyi",
    宁采臣: "Ning Choi-san",
    旭仔: "Yuddy",
    欧阳锋: "Ouyang Feng",
    何宝荣: "Ho Po-wing",
    秋菊: "Qiu Ju",
    颂莲: "Songlian",
    菊豆: "Ju Dou",
    女皇: "Empress",
    冯婉瑜: "Feng Wanyu",
    玉娇龙: "Jen Yu",
    宫二: "Gong Er",
    小妹: "Xiao Mei",
    赵弟: "Zhao Di",
    白玲: "Bai Ling",
    黎叔: "Uncle Li",
    秦奋: "Qin Fen",
    姚远: "Yao Yuan",
    严守一: "Yan Shouyi",
    福贵: "Fugui",
    史提芬周: "Stephen Chow",
    人字拖: "Thongs",
    无名: "Nameless",
    钟天正: "Chung Tin-ching",
    黎耀辉: "Lai Yiu-fai",
    十二少: "Twelfth Master",
    菊仙: "Juxian",
    王敏佳: "Wang Minjia",
    李冬宝: "Li Dongbao",
    场记板: "Clapperboard",
    爆米花补给: "Popcorn Resupply",
    武术指导: "Fight Choreographer",
    替身演员: "Stunt Double",
    威亚救场: "Wirework Rescue",
    经典台词: "Classic Line",
    导演喊卡: "Director Calls Cut",
    黄金档播出: "Prime-Time Premiere",
    训练蒙太奇: "Training Montage",
    雨夜巷战: "Rainy Alley Fight",
    群演入镜: "Extras Enter Frame",
    片尾彩蛋: "Post-Credits Scene",
    票房逆袭: "Box-Office Comeback",
    老戏骨压场: "Veteran Takes the Stage",
    主题曲响起: "Theme Song Rises",
    胶片倒带: "Film Rewind",
    双雄合璧: "Twin Heroes Unite",
    宿命交锋: "Fated Showdown",
    以牙还牙: "An Eye for an Eye",
    终场遗言: "Final Words",
    大场面爆破: "Blockbuster Explosion",
    绝地重拍: "Last-Chance Reshoot",
    反派独白: "Villain's Monologue",
    金牌剪辑: "Masterful Edit",
    主角光环: "Protagonist's Aura",
    命运反转: "Twist of Fate",
    金箍棒: "Golden Cudgel",
    青冥剑: "Green Destiny",
    凌凌漆飞刀: "Ling Ling-chat's Throwing Knife",
    小马哥双枪: "Mark's Twin Pistols",
    赌神扑克牌: "God of Gamblers' Cards",
    倚天剑: "Heaven Sword",
    普通群演: "Background Extra",
    巡街警员: "Patrol Officer",
    酒馆伙计: "Tavern Hand",
    临时加戏: "Improvised Scene",
    喜剧搭档: "Comedy Partner",
    镖局护卫: "Escort Guard",
    年轻捕快: "Young Constable",
    基础长棍: "Basic Staff",
    武馆教头: "Martial Arts Instructor",
    客栈女侠: "Inn Swordswoman",
    重案探员: "Major Crimes Detective",
    街坊助阵: "Neighborhood Backup",
    醉侠随从: "Drunken Hero's Follower",
    客栈伏击: "Inn Ambush",
    短锋剑: "Short-Edge Sword",
    血滴子死士: "Flying Guillotine Zealot",
    飞索锁敌: "Flying Chain Snare",
    血滴子: "Flying Guillotine",
    蜈蚣门徒: "Centipede Disciple",
    蛇形换位: "Serpent Step",
    毒门钢刺: "Venom Steel Spike",
    金臂门卫: "Golden Arm Guard",
    铁布衫: "Iron Shirt",
    金臂护腕: "Golden Arm Bracer",
    白莲弟子: "White Lotus Disciple",
    莲台护法: "Lotus Altar Guardian",
    回马枪: "Turning Spear",
    金燕子: "Golden Swallow",
    方刚: "Fang Gang",
    三德和尚: "San Te",
    玉面虎: "Jade-Faced Tiger",
    血滴子统领: "Flying Guillotine Commander",
    蜈蚣: "Centipede",
    金臂童: "Golden Arm Kid",
    白莲教主: "White Lotus Chief",
    山寨喽啰: "Bandit Minion",
    侍卫: "Royal Guard",
    厨房学徒: "Kitchen Apprentice",
    如花幻影: "Ru Hua's Phantom",
    少林学徒: "Shaolin Student",
    护婴拍档: "Babysitting Partner",
    捧哏: "Comedy Sidekick",
    替身主角: "Stunt Lead",
    水手: "Sailor",
    狱友: "Cellmate",
    群演: "Extra",
    老戏骨: "Veteran Actor",
    街坊: "Neighbor",
    燕影: "Swallow Shadow",
    毒门伏兵: "Venom Ambusher",
    白莲香众: "White Lotus Acolyte",
    木人桩: "Wooden Dummy",
    断刃: "Broken Blade",
    融合主角: "Fusion Lead",
    银幕双雄: "Silver-Screen Duo",
    宿命主角: "Fated Lead",
  };
});
