(function (root, factory) {
  const translations = factory();
  if (typeof module === "object" && module.exports) {
    module.exports = translations;
  }
  if (root) root.MOVIE_BRAWL_ENTITIES_EN = translations;
})(typeof window !== "undefined" ? window : null, function () {
  return {
    周星驰: "Stephen Chow",
    成龙: "Jackie Chan",
    李连杰: "Jet Li",
    周润发: "Chow Yun-fat",
    刘德华: "Andy Lau",
    梁朝伟: "Tony Leung Chiu-wai",
    张国荣: "Leslie Cheung",
    巩俐: "Gong Li",
    章子怡: "Zhang Ziyi",
    葛优: "Ge You",
    郑佩佩: "Cheng Pei-pei",
    王羽: "Jimmy Wang Yu",
    刘家辉: "Gordon Liu",
    通用: "Neutral",
    基础卡: "Basic Set",
    邵氏群像: "Shaw Ensemble",
    邵氏片场: "Shaw Studio",
    片场法术: "Studio Spell",
    银幕武器: "Screen Weapon",
    金像影迷: "Golden Reel Fan",
    反派制片方: "Villainous Producer",
    影迷: "Movie Fan",
    影迷英雄: "Movie Fan Hero",
    反派制片方英雄: "Villainous Producer Hero",
    至尊宝: "Joker",
    唐伯虎: "Tong Pak-fu",
    凌凌漆: "Ling Ling-chat",
    尹天仇: "Wan Tin-sau",
    星仔: "Sing",
    陈家驹: "Chan Ka-kui",
    黄飞鸿: "Wong Fei-hung",
    马如龙: "Dragon Ma",
    孟波: "Meng Bo",
    杰克: "Jack",
    令狐冲: "Linghu Chong",
    方世玉: "Fong Sai-yuk",
    张无忌: "Zhang Wuji",
    霍元甲: "Huo Yuanjia",
    小马哥: "Mark Lee",
    许文强: "Hui Man-keung",
    高进: "Ko Chun",
    李慕白: "Li Mu Bai",
    阿郎: "Ah-Long",
    华弟: "Wah Dee",
    华仔: "Ah Wah",
    刘建明: "Lau Kin-ming",
    刀仔: "Little Knife",
    雷洛: "Lee Rock",
    杨过: "Yang Guo",
    陈永仁: "Chan Wing-yan",
    周慕云: "Chow Mo-wan",
    盲武士: "Blind Swordsman",
    韦小宝: "Wai Siu-bo",
    叶问: "Ip Man",
    程蝶衣: "Cheng Dieyi",
    宁采臣: "Ning Choi-san",
    旭仔: "Yuddy",
    欧阳锋: "Ouyang Feng",
    何宝荣: "Ho Po-wing",
    秋菊: "Qiu Ju",
    颂莲: "Songlian",
    菊豆: "Ju Dou",
    女皇: "Empress",
    冯婉瑜: "Feng Wanyu",
    玉娇龙: "Jen Yu",
    宫二: "Gong Er",
    小妹: "Xiao Mei",
    赵弟: "Zhao Di",
    白玲: "Bai Ling",
    黎叔: "Uncle Li",
    秦奋: "Qin Fen",
    姚远: "Yao Yuan",
    严守一: "Yan Shouyi",
    福贵: "Fugui",
    史提芬周: "Stephen Chow",
    人字拖: "Thongs",
    无名: "Nameless",
    钟天正: "Chung Tin-ching",
    黎耀辉: "Lai Yiu-fai",
    十二少: "Twelfth Master",
    菊仙: "Juxian",
    王敏佳: "Wang Minjia",
    李冬宝: "Li Dongbao",
    场记板: "Clapperboard",
    爆米花补给: "Popcorn Resupply",
    武术指导: "Fight Choreographer",
    替身演员: "Stunt Double",
    威亚救场: "Wirework Rescue",
    经典台词: "Classic Line",
    导演喊卡: "Director Calls Cut",
    黄金档播出: "Prime-Time Premiere",
    训练蒙太奇: "Training Montage",
    雨夜巷战: "Rainy Alley Fight",
    群演入镜: "Extras Enter Frame",
    片尾彩蛋: "Post-Credits Scene",
    票房逆袭: "Box-Office Comeback",
    老戏骨压场: "Veteran Takes the Stage",
    主题曲响起: "Theme Song Rises",
    胶片倒带: "Film Rewind",
    双雄合璧: "Twin Heroes Unite",
    宿命交锋: "Fated Showdown",
    以牙还牙: "An Eye for an Eye",
    终场遗言: "Final Words",
    大场面爆破: "Blockbuster Explosion",
    绝地重拍: "Last-Chance Reshoot",
    反派独白: "Villain's Monologue",
    金牌剪辑: "Masterful Edit",
    主角光环: "Protagonist's Aura",
    命运反转: "Twist of Fate",
    金箍棒: "Golden Cudgel",
    青冥剑: "Green Destiny",
    凌凌漆飞刀: "Ling Ling-chat's Throwing Knife",
    小马哥双枪: "Mark's Twin Pistols",
    赌神扑克牌: "God of Gamblers' Cards",
    倚天剑: "Heaven Sword",
    普通群演: "Background Extra",
    巡街警员: "Patrol Officer",
    酒馆伙计: "Tavern Hand",
    临时加戏: "Improvised Scene",
    喜剧搭档: "Comedy Partner",
    镖局护卫: "Escort Guard",
    年轻捕快: "Young Constable",
    基础长棍: "Basic Staff",
    武馆教头: "Martial Arts Instructor",
    客栈女侠: "Inn Swordswoman",
    重案探员: "Major Crimes Detective",
    街坊助阵: "Neighborhood Backup",
    醉侠随从: "Drunken Hero's Follower",
    客栈伏击: "Inn Ambush",
    短锋剑: "Short-Edge Sword",
    血滴子死士: "Flying Guillotine Zealot",
    飞索锁敌: "Flying Chain Snare",
    血滴子: "Flying Guillotine",
    蜈蚣门徒: "Centipede Disciple",
    蛇形换位: "Serpent Step",
    毒门钢刺: "Venom Steel Spike",
    金臂门卫: "Golden Arm Guard",
    铁布衫: "Iron Shirt",
    金臂护腕: "Golden Arm Bracer",
    白莲弟子: "White Lotus Disciple",
    莲台护法: "Lotus Altar Guardian",
    回马枪: "Turning Spear",
    金燕子: "Golden Swallow",
    方刚: "Fang Gang",
    三德和尚: "San Te",
    玉面虎: "Jade-Faced Tiger",
    血滴子统领: "Flying Guillotine Commander",
    蜈蚣: "Centipede",
    金臂童: "Golden Arm Kid",
    白莲教主: "White Lotus Chief",
    山寨喽啰: "Bandit Minion",
    侍卫: "Royal Guard",
    厨房学徒: "Kitchen Apprentice",
    如花幻影: "Ru Hua's Phantom",
    少林学徒: "Shaolin Student",
    护婴拍档: "Babysitting Partner",
    捧哏: "Comedy Sidekick",
    替身主角: "Stunt Lead",
    水手: "Sailor",
    狱友: "Cellmate",
    群演: "Extra",
    老戏骨: "Veteran Actor",
    街坊: "Neighbor",
    燕影: "Swallow Shadow",
    毒门伏兵: "Venom Ambusher",
    白莲香众: "White Lotus Acolyte",
    木人桩: "Wooden Dummy",
    断刃: "Broken Blade",
    融合主角: "Fusion Lead",
    银幕双雄: "Silver-Screen Duo",
    宿命主角: "Fated Lead",
    李小龙: "Bruce Lee",
    嘉禾片场: "Golden Harvest Studio",
    嘉禾群像: "Golden Harvest Ensemble",
    片场: "Studio",
    冰厂工友: "Ice Factory Worker",
    冰厂突围: "Factory Breakout",
    双节棍: "Nunchaku",
    纸扎替身: "Paper Effigy Double",
    定身灵符: "Binding Talisman",
    桃木剑: "Peachwood Sword",
    茶壶: "Teapot",
    五星合拍: "Five-Star Teamwork",
    逃脱面包车: "Getaway Van",
    战地队员: "Field Operative",
    丛林伏击: "Jungle Ambush",
    军用匕首: "Combat Knife",
    宝芝林弟子: "Po Chi Lam Disciple",
    佛山无影脚: "Foshan Shadowless Kick",
    宝芝林长棍: "Po Chi Lam Staff",
    唐龙: "Tang Lung",
    米老板: "Boss Mi",
    钱真人: "Sorcerer Chin",
    冷面杀手: "Stone-Faced Killer",
    将军: "The General",
    严振东: "Yim Chun-tung",
    冰厂打手: "Ice Factory Enforcer",
    纸人: "Paper Effigy",
    福星拍档: "Lucky Star Partner",
    重案警员: "Major Crimes Officer",
    突击队员: "Assault Trooper",
    醒狮桩: "Lion Post",
    醒狮队员: "Lion Dancer",
    罗马拳手: "Roman Fighter",
    许冠杰: "Sam Hui",
    林青霞: "Brigitte Lin",
    狄龙: "Ti Lung",
    新艺城片场: "Cinema City Studio",
    新艺城群像: "Cinema City Ensemble",
    林亚珍: "Jane",
    智多星布局: "Mastermind Scheme",
    机关雨伞: "Gadget Umbrella",
    古志明: "Chi-ming",
    小瑜: "Siu-yu",
    人鬼错摸: "Mortal-Spirit Mix-up",
    开心少女: "Happy Schoolgirl",
    青春愿望: "Youthful Wish",
    校园接力棒: "School Relay Baton",
    高秋: "Ko Chow",
    天台暗号: "Rooftop Signal",
    警用左轮: "Police Revolver",
    狱中拍档: "Prison Partner",
    牢房换位: "Cellblock Switch",
    饭堂铁盘: "Canteen Tray",
    "King Kong": "King Kong",
    曹云: "Tsao Wan",
    宋子豪: "Sung Tse-ho",
    赌局庄家: "The House Dealer",
    还魂倩影: "Returning Spirit",
    开心鬼: "Happy Ghost",
    阿虎: "Fu",
    杀手雄: "Officer Scarface",
    奋斗房拍档: "Striving Room Partner",
    错摸幻影: "Mix-up Phantom",
    高科技拍档: "Hi-Tech Partner",
    开心同学: "Happy Classmate",
    戏班同伴: "Opera Companion",
    义气拍档: "Brotherhood Partner",
    杨紫琼: "Michelle Yeoh",
    德宝片场: "D & B Studio",
    德宝群像: "D & B Ensemble",
    吴阿秋: "Ah Chau",
    贝多芬: "Beethoven",
    警车包抄: "Police Car Pincer",
    骠叔: "Mr Bill",
    骠婶: "Mrs Bill",
    横财彩票: "Winning Lottery Ticket",
    徐先生: "Mr Tsui",
    叶姑娘: "Miss Yip",
    街头支援: "Street Outreach",
    霍明明: "Ming-ming",
    战地电台: "Field Radio",
    飞行索具: "Aerial Rig",
    阿雄: "Hung",
    Mimi: "Mimi",
    旺角接应: "Mong Kok Backup",
    吴洛茜: "Inspector Ng",
    船头尺: "Samuel Pang",
    叶剑飞: "Yip Kim-fai",
    吴阿秋与贝多芬: "Ah Chau and Beethoven",
    骠叔一家: "The Bill Family",
    巡逻警员: "Patrol Officer",
    社区义工: "Community Volunteer",
    街头接应: "Street Backup",
    黎明同伴: "Dawn Companion",
    皇家探员: "Royal Inspector",
    唐人街邻里: "Chinatown Neighbor",
    国际动作队员: "International Stunt Operative",
    黎明守望者: "Dawn Watcher",
    梅艳芳: "Anita Mui",
    金公主院线: "Golden Princess Circuit",
    金公主群像: "Golden Princess Ensemble",
    李鹰: "Inspector Li",
    教堂白鸽: "Church Doves",
    警探配枪: "Detective's Sidearm",
    兰若夜雨: "Rain over Lan Ro Temple",
    桃木法剑: "Peachwood Ritual Sword",
    父子冲线: "Father and Son Finish",
    旧赛道头盔: "Old Racing Helmet",
    笑傲曲谱: "Smiling Proud Score",
    独孤长剑: "Dugu Longsword",
    JoJo: "JoJo",
    亡命摩托: "Runaway Motorcycle",
    小庄: "Ah Jong",
    周英杰: "Chow Ying-kit",
    袁浩云: "Inspector Tequila Yuen",
    黑山老妖: "Black Mountain Demon",
    汪海: "Wong Hoi",
    大赛车手: "Champion Racer",
    任我行: "Ren Woxing",
    七哥: "Brother Seven",
    兰若幽灯: "Lan Ro Spirit Lantern",
    持枪杀手: "Contract Gunman",
    赛道学徒: "Track Apprentice",
    逃生同伴: "Escape Companion",
    越境手枪: "Border Pistol",
    曲谱剑客: "Score Swordsman",
    午夜摩托手: "Midnight Rider",
    子夜重案警员: "Midnight Detective",
    刘青云: "Sean Lau",
    黄秋生: "Anthony Wong",
    任达华: "Simon Yam",
    银河映像: "Milkyway Image",
    黄阿狗: "Doggie",
    命运岔路: "Fork in Fate",
    江湖硬币: "Underworld Coin",
    阿琛: "Sam",
    关闸暗号: "Border Gate Signal",
    凌晨左轮: "Midnight Revolver",
    阿鬼: "Curtis",
    商场站位: "Mall Formation",
    保镖手枪: "Bodyguard Pistol",
    乐少: "Lok",
    龙头棍: "Dragon Head Baton",
    票箱点算: "Ballot Count",
    阿火: "Blaze",
    澳门饭局: "Macau Dinner",
    旧式手枪: "Old Service Pistol",
    张彼德: "Cheung Peter",
    何文展: "Sergeant Ho",
    陈桂彬: "Bun",
    命运庄家: "Dealer of Fate",
    洪先生: "Mr Hung",
    文哥: "Boss Lung",
    大D: "Big D",
    大飞: "Boss Fay",
    江湖路人: "Underworld Drifter",
    静默保镖: "Silent Bodyguard",
    PTU警员: "PTU Officer",
    社团票委: "Ballot Committee Member",
    社团护票: "Ballot Guard",
    追兵: "Pursuer",
    进取人格: "Aggressive Persona",
    恐惧人格: "Fearful Persona",
  };
});
