(function (root, factory) {
  const translations = factory();
  if (typeof module === "object" && module.exports) {
    module.exports = translations;
  }
  if (root) root.MOVIE_BRAWL_MOVIES_EN = translations;
})(typeof window !== "undefined" ? window : null, function () {
  return {
    大话西游: "A Chinese Odyssey",
    唐伯虎点秋香: "Flirting Scholar",
    国产凌凌漆: "From Beijing with Love",
    喜剧之王: "King of Comedy",
    功夫: "Kung Fu Hustle",
    警察故事: "Police Story",
    醉拳: "Drunken Master",
    A计划: "Project A",
    城市猎人: "City Hunter",
    神话: "The Myth",
    笑傲江湖之东方不败: "Swordsman II",
    黄飞鸿: "Once Upon a Time in China",
    方世玉: "The Legend of Fong Sai-yuk",
    倚天屠龙记之魔教教主: "Kung Fu Cult Master",
    霍元甲: "Fearless",
    英雄本色: "A Better Tomorrow",
    上海滩: "The Bund",
    赌神: "God of Gamblers",
    卧虎藏龙: "Crouching Tiger, Hidden Dragon",
    阿郎的故事: "All About Ah-Long",
    天若有情: "A Moment of Romance",
    无间道: "Infernal Affairs",
    赌侠: "God of Gamblers II",
    五亿探长雷洛传: "Lee Rock",
    神雕侠侣: "The Return of the Condor Heroes",
    花样年华: "In the Mood for Love",
    东邪西毒: "Ashes of Time",
    鹿鼎记: "Royal Tramp",
    一代宗师: "The Grandmaster",
    霸王别姬: "Farewell My Concubine",
    倩女幽魂: "A Chinese Ghost Story",
    阿飞正传: "Days of Being Wild",
    春光乍泄: "Happy Together",
    秋菊打官司: "The Story of Qiu Ju",
    大红灯笼高高挂: "Raise the Red Lantern",
    菊豆: "Ju Dou",
    满城尽带黄金甲: "Curse of the Golden Flower",
    归来: "Coming Home",
    十面埋伏: "House of Flying Daggers",
    我的父亲母亲: "The Road Home",
    "2046": "2046",
    天下无贼: "A World Without Thieves",
    非诚勿扰: "If You Are the One",
    不见不散: "Be There or Be Square",
    手机: "Cell Phone",
    活着: "To Live",
    食神: "The God of Cookery",
    宝贝计划: "Rob-B-Hood",
    英雄: "Hero",
    监狱风云: "Prison on Fire",
    旺角卡门: "As Tears Go By",
    胭脂扣: "Rouge",
    无问西东: "Forever Young",
    编辑部的故事: "Stories from the Editorial Board",
    片场通用: "Studio General",
    影院通用: "Cinema General",
    动作片通用: "Action Film General",
    华语片通用: "Chinese-Language Film General",
    电视剧通用: "Television General",
    类型片通用: "Genre Film General",
    警匪片通用: "Crime Film General",
    商业片通用: "Commercial Film General",
    院线通用: "Theatrical General",
    群像片通用: "Ensemble Film General",
    经典片通用: "Classic Film General",
    怀旧片通用: "Nostalgia Film General",
    双主角通用: "Dual-Protagonist General",
    剧情片通用: "Drama General",
    续集通用: "Sequel General",
    犯罪片通用: "Crime Drama General",
    传奇片通用: "Legendary Tale General",
    片场日常: "A Day on Set",
    警匪行动: "Police Operation",
    江湖客栈: "Wuxia Inn",
    动作片场: "Action Set",
    市井喜剧: "Street Comedy",
    江湖武侠: "Wandering Swordsmen",
    功夫训练: "Kung Fu Training",
    大醉侠: "Come Drink with Me",
    血滴子: "The Flying Guillotine",
    五毒: "Five Deadly Venoms",
    金臂童: "Kid with the Golden Arm",
    洪文定三破白莲教: "Clan of the White Lotus",
    独臂刀: "The One-Armed Swordsman",
    少林三十六房: "The 36th Chamber of Shaolin",
    唐山大兄: "The Big Boss",
    鬼打鬼: "Encounters of the Spooky Kind",
    奇谋妙计五福星: "Winners and Sinners",
    东方秃鹰: "Eastern Condors",
    猛龙过江: "The Way of the Dragon",
    鬼马智多星: "All the Wrong Clues",
    阴阳错: "Esprit d'Amour",
    最佳拍档: "Aces Go Places",
    开心鬼: "Happy Ghost",
    刀马旦: "Peking Opera Blues",
    龙虎风云: "City on Fire",
    双龙出海: "The Return of Pom Pom",
    富贵逼人: "It's a Mad, Mad, Mad World",
    皇家师姐: "Yes, Madam!",
    癫佬正传: "The Lunatics",
    秋天的童话: "An Autumn's Tale",
    中华战士: "Magnificent Warriors",
    最后胜利: "Final Victory",
    等待黎明: "Hong Kong 1941",
    喋血双雄: "The Killer",
    英雄本色III夕阳之歌: "A Better Tomorrow III",
    笑傲江湖: "Swordsman",
    辣手神探: "Hard Boiled",
    临时登场: "Cameo Appearance",
  };
});
